apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: wg2-flux-integraion
  namespace: flux-system
spec:
  interval: 30m
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
